XE-4579 templates for icons, fixes components, and fixes params that are functions
buildium/angular-docs pull request #2
Opened 2018-06-20 20:42 UTC by saltavenger

- Adds templates for various kinds of images we have
- Adds a template for components to fix usage examples showing up with blank params
- Fixes param types so that params that are functions don't show up with a blank example

2018-06-21 15:00 UTC, saltavenger commented
Some screenshots to illustrate changes:
https://www.screencast.com/t/yqx11pPOYge9
https://www.screencast.com/t/ST24V07I9

2018-06-21 15:01 UTC, sngan-buildium approved these changes

2018-06-22 03:34 UTC, digitil requested changes
this feels like a *minor* version change since we've added the ability to document new things

2018-06-22 15:29 UTC, digitil approved these changes

2018-06-22 15:50 UTC, merged